// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Tonex_Controller

#include "ui.h"

void PreviousClicked(lv_event_t * e)
{
	// Your code here
}

void NextClicked(lv_event_t * e)
{
	// Your code here
}

void BankAClicked(lv_event_t * e)
{
	// Your code here
}

void BankBClicked(lv_event_t * e)
{
	// Your code here
}

void AmpSkinPrevious(lv_event_t * e)
{
	// Your code here
}

void AmpSkinNext(lv_event_t * e)
{
	// Your code here
}

void PresetDescriptionChanged(lv_event_t * e)
{
	// Your code here
}

void SaveUserDataRequest(lv_event_t * e)
{
	// Your code here
}

void BTBondsClearRequest(lv_event_t * e)
{
	// Your code here
}

void ParameterChanged(lv_event_t * e)
{
	// Your code here
}

void toggle_effect_gate(lv_event_t * e)
{
	// Your code here
}

void toggle_effect_amp(lv_event_t * e)
{
	// Your code here
}

void toggle_effect_cab(lv_event_t * e)
{
	// Your code here
}

void toggle_effect_comp(lv_event_t * e)
{
	// Your code here
}

void toggle_effect_mod(lv_event_t * e)
{
	// Your code here
}

void toggle_effect_delay(lv_event_t * e)
{
	// Your code here
}

void toggle_effect_reverb(lv_event_t * e)
{
	// Your code here
}

void show_settings_tab_gate(lv_event_t * e)
{
	// Your code here
}

void show_settings_tab(lv_event_t * e)
{
	// Your code here
}

void PresetClicked1(lv_event_t * e)
{
	// Your code here
}

void PresetClicked2(lv_event_t * e)
{
	// Your code here
}

void PresetClicked3(lv_event_t * e)
{
	// Your code here
}

void PresetClicked4(lv_event_t * e)
{
	// Your code here
}

void PreviousBankClicked(lv_event_t * e)
{
	// Your code here
}

void NextBankClicked(lv_event_t * e)
{
	// Your code here
}

void PreviousBank(lv_event_t * e)
{
	// Your code here
}

void NextBank(lv_event_t * e)
{
	// Your code here
}

void PreviousButton(lv_event_t * e)
{
	// Your code here
}

void NextButton(lv_event_t * e)
{
	// Your code here
}

void FS7Action(lv_event_t * e)
{
	// Your code here
}

void FS6Action(lv_event_t * e)
{
	// Your code here
}

void AltButtonAction(lv_event_t * e)
{
	// Your code here
}

void FS9Action(lv_event_t * e)
{
	// Your code here
}

void TapTempoAction(lv_event_t * e)
{
	// Your code here
}
