#include "images.h"

const ext_img_desc_t images[22] = {
    { "next", &img_next },
    { "next_down", &img_next_down },
    { "previous", &img_previous },
    { "previous_down", &img_previous_down },
    { "amp", &img_amp },
    { "cab", &img_cab },
    { "comp", &img_comp },
    { "delay-digital", &img_delay_digital },
    { "delay-tape", &img_delay_tape },
    { "eq", &img_eq },
    { "gate", &img_gate },
    { "mod-chorus", &img_mod_chorus },
    { "mod-flanger", &img_mod_flanger },
    { "mod-phaser", &img_mod_phaser },
    { "mod-rotary", &img_mod_rotary },
    { "mod-tremolo", &img_mod_tremolo },
    { "reverb-plate", &img_reverb_plate },
    { "reverb-room", &img_reverb_room },
    { "reverb-spring-1", &img_reverb_spring_1 },
    { "reverb-spring-2", &img_reverb_spring_2 },
    { "reverb-spring-3", &img_reverb_spring_3 },
    { "reverb-spring-4", &img_reverb_spring_4 },
};